### PR TITLE
Moved index.html to html folder, and added class for h2 in year.html

### PR DESCRIPTION
**Pull request by shreygupta2809**

### CODE REVIEW

**Comment by shreygupta2809** [comment]
@gsc2001 @Chief-Blackhood @tichnas please review

**Comment by shreygupta2809** [comment]
i have moved index.html to html folder
The year.html is still in html folder outside of resources

**Review by gsc2001 — APPROVED** [review]
Ok.

**Comment by gsc2001** [comment]
I think dont add class name because i will be using h2 on home page

**Comment by gsc2001** [comment]
closes #36. closes #35.

**Comment by gsc2001** [comment]
While merging add 'closes  #36 and closes #41 ' in commit messege

**Review by Chief-Blackhood — APPROVED** [review]

**Review by tichnas — CHANGES_REQUESTED** [review]
index.html can't be inside html folder. For any website, we must put index.html in root directory (refer your iiit website). Also, maybe we can put the html folder inside resources (doesn't matter much)?

**Comment by gsc2001** [comment]
Its ok

**Pull request merged**
