### PR TITLE
Feature/year template Closes #30

### LINKED ISSUE #30: JS and template for year.html
Will be creating template for creating year webpage template

### PR DESCRIPTION
**Pull request by gsc2001**
All year htmls and linking with proper functioning of bookmarks

### CODE REVIEW

**Comment by gsc2001** [comment]
Closes #30

**Comment by shreygupta2809** [comment]
Do not merge now

**Review by tichnas — APPROVED** [review]

**Review by tichnas — CHANGES_REQUESTED** [review]
I think it will be better if we put all html files in /resources/html

**Comment by gsc2001** [comment]
Everything done
Bookmark fixed

**Comment by gsc2001** [comment]
Please first merge this and then change the folder

**Review by shreygupta2809 — APPROVED** [review]

**Comment by shreygupta2809** [comment]
@tichnas @Chief-Blackhood

**Comment by Chief-Blackhood** [comment]
Thik hai

**Pull request merged**
